version: "3.8"

# DOCKER_BUILDKIT=1  docker compose -f graalvm-compose.yml up
# DOCKER_BUILDKIT=1  docker compose -f graalvm-compose.yml up --build native-image-amd64
# DOCKER_BUILDKIT=1  docker compose -f graalvm-compose.yml up --build native-image-arm64
services:
  native-image-amd64:
    container_name: app-linux-amd64
    build:
      context: .
      target: graalvm-static
      args:
        JDK_VERSION: 17
    platform: linux/amd64
    volumes:
      - ./:/src:rw
    command: [ "./httpserver" ]
    ports:
      - "8081:80"
    networks:
      - app-network

  native-image-arm64:
    container_name: app-linux-arm64
    build:
      context: .
      target: graalvm-static
      args:
        JDK_VERSION: 17
    platform: linux/arm64
    volumes:
      - ./:/src:rw
    command: [ "./httpserver" ]
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network: