# Set global options
data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = true
address = "0.0.0.0:8686"

# Original source
[sources.generate_syslog]
type = "demo_logs"
format = "syslog"
count = 100
interval = 0.5

# Enrich with more data.
[transforms.add_host]
inputs = ["generate_syslog"]
type = "remap"
source = '''
  .host = "${HOSTNAME}"
  .env = "${ENV:-dev}"
'''

# Additional  transformation
[transforms.remap_syslog]
inputs = ["add_host"]
type = "remap"
source = '''
  structured = parse_syslog!(.message)
  . = merge(., structured)
'''

[sinks.emit_syslog]
inputs = ["remap_syslog"]
type = "console"
encoding.codec = "json"

# Ingest data by tailing one or more files
[sources.apache_logs]
type = "file"
include = ["/var/log/apache2/*.log"]    # supports globbing
ignore_older = 86400                    # 1 day
