version: "3.8"

# docker compose -f graalvm-compose.yml up

# Some time build with --no-cache required for forcefully rebuild the image
# docker compose -f graalvm-compose.yml build --no-cache app-arm64

# docker compose -f graalvm-compose.yml up --remove-orphans --build app-arm64
# docker compose -f graalvm-compose.yml up --remove-orphans --build app-amd64
name: native-image

services:
  app-amd64:
    container_name: ${NI_NAME_AMD64}
    build:
      context: ..
      target: graalvm-static
      # args:
      #  GRAAL_JDK_VERSION: 17
    platform: linux/amd64
    command: [ "${NI_NAME_AMD64:-amd64}" ]
    environment:
      - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - CONTAINER_NAME=${NI_NAME_AMD64}
    volumes:
      - ./:/src:rw
    ports:
      - "9000:80"
    networks:
      - app-network

  app-arm64:
    container_name: ${NI_NAME_ARM64}
    build:
      context: ..
      target: graalvm-static
    platform: linux/arm64
    command: [ "${NI_NAME_ARM64:-arm64}" ]
    environment:
      - PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - CONTAINER_NAME=${NI_NAME_ARM64}
    volumes:
      - ./:/src:rw
    ports:
      - "9001:80"
    networks:
      - app-network

networks:
  app-network:
