version: "3.8"

# docker compose -f tcpdump-compose.yml up
services:
  app:
    build:
      context: ..
      target: openjdk
    container_name: app
    restart: always
    volumes:
      - ./:/data:rw
    tmpfs:
      - /test
    command: [ "java", "--show-version", "--enable-preview", "-jar", "app.jar" ]
    ports:
      - "8080:80"
    networks:
      - app-network

  load-gen:
    image: peterevans/vegeta:latest
    container_name: vegeta
    # restart: always
    networks:
      - app-network
    command: [ "/bin/sh","-c","echo 'GET http://app/test' | vegeta attack -rate=2 -duration=60s -name=App  | tee results.bin | vegeta report" ]
    depends_on:
      - app

  tcpdump:
    image: nicolaka/netshoot:latest
    container_name: tcpdump
    restart: always
    network_mode: container:app
    command: [ "tcpdump", "-A", "-s", "0", "tcp port 80 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)" ]
    depends_on:
      - app

networks:
  app-network: