version: "3.8"

# docker compose -f tcpdump-compose.yml up
services:
  app:
    build:
      context: .
      target: openjdk
    container_name: app
    restart: always
    volumes:
      - ./:/data:rw
    tmpfs:
      - /test
    command: [ "java", "--show-version", "-jar", "app.jar" ]
    ports:
      - "8080:80"
    networks:
      - app-network

  load-gen:
    image: peterevans/vegeta:latest
    container_name: vegeta
    # restart: always
    networks:
      - app-network
    command: [ "/bin/sh","-c","echo 'GET http://app/test' | vegeta attack -rate=10 -duration=5s -name=App  | tee results.bin | vegeta report" ]
    depends_on:
      - app

  tcpdump:
    image: nicolaka/netshoot:latest
    container_name: tcpdump
    restart: always
    network_mode: container:app
    networks:
      - app-network
    command: [ "tcpdump" ]
    depends_on:
      - app

networks:
  app-network: